# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0015_recipeweek_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeweek',
            name='week',
            field=models.SmallIntegerField(default=29),
        ),
    ]
