# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-27 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0016_auto_20170717_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recipeweek',
            name='week',
            field=models.SmallIntegerField(default=34),
        ),
        migrations.AddField(
            model_name='recipe',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.Season'),
        ),
    ]
