# Generated by Django 2.0.1 on 2018-02-02 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0018_auto_20170827_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.SmallIntegerField(default=5)),
                ('year', models.SmallIntegerField(default=2018)),
                ('fresh', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('sort', models.SmallIntegerField(default=0)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='menus.RecipeIngredients')),
            ],
        ),
        migrations.CreateModel(
            name='SupermarketCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupermarketWoolworth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockcode', models.SmallIntegerField()),
                ('cost', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.SupermarketCategory')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.Ingredients')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipeweek',
            name='cost',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='primaryType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menus.PrimaryType'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menus.Season'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='secondaryType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menus.SecondaryType'),
        ),
        migrations.AlterField(
            model_name='recipeweek',
            name='week',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='recipeweek',
            name='year',
            field=models.SmallIntegerField(default=2018),
        ),
    ]
