# Generated by Django 2.0.1 on 2018-02-03 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0021_auto_20180202_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='ingredient',
            new_name='recipeingredient',
        ),
    ]
