# Generated by Django 2.0.1 on 2018-02-03 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0022_auto_20180203_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='recipeingredient',
            new_name='recipeIngredient',
        ),
    ]
