# Generated by Django 2.0.1 on 2018-02-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0023_auto_20180203_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
