# Generated by Django 2.1.3 on 2018-11-15 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0027_auto_20181115_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountuser',
            old_name='userId',
            new_name='name',
        ),
    ]
