# Generated by Django 2.1.3 on 2018-11-15 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0029_auto_20181115_0307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='RecipeIngredients',
            new_name='RecipeIngredient',
        ),
    ]
