# Generated by Django 2.1.3 on 2018-11-15 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0031_auto_20181115_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
