# Generated by Django 2.1.3 on 2018-11-15 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0032_auto_20181115_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeweek',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.Account'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menus.Account'),
        ),
    ]
