# Generated by Django 2.1.3 on 2018-11-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0034_auto_20181116_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='filename',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
