# Generated by Django 2.1.3 on 2018-11-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0037_auto_20181116_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrecipe',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
