# Generated by Django 2.1.3 on 2018-11-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0038_accountrecipe_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipeweek',
            name='week',
            field=models.SmallIntegerField(default=47),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='week',
            field=models.SmallIntegerField(default=47),
        ),
    ]
