# Generated by Django 2.1.3 on 2018-11-19 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0041_remove_accountingredient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingredient',
            name='category',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to='menus.SupermarketCategory'),
        ),
    ]
