# Generated by Django 2.1.3 on 2018-11-20 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0042_accountingredient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menus.Ingredient'),
        ),
    ]
